site_name: Application Documentation

nav:
  - Home: index.md
  - Overview: overview.md
  - MongoDB: mongo_setup.md
  - Python: python_setup.md
  - Local Setup: local_app_setup.md
  - App Usage: application_usage.md

theme:
  name: readthedocs
